### ISSUE TITLE
Poetry fails with either install method on Kali

### ISSUE THREAD

**Issue by pk-r7** [byt3bl33d3r/ItWasAllADream#18]
Version 6.1.20-1kali1 (2023-03-22)

`Installing dependencies from lock file

Because impacket (0.10.1.dev1+20230413.195351.6328a9b7) @ git+https://github.com/SecureAuthCorp/impacket.git@HEAD depends on dsinternals (*) which doesn't match any versions, impacket is forbidden.                                                                                                                                 
So, because itwasalladream depends on impacket (0.10.1.dev1+20230413.195351.6328a9b7) @ git+https://github.com/SecureAuthCorp/impacket.git, version solving failed.
              `
Also tried updating link to fortra, did not make a difference

**Comment by d0MeGaSt4** [comment]
Hey @pk-mdt @byt3bl33d3r . I keep getting this same error. Do you manage to get it fixed? I also referenced this link on impacket but I already have disinternals installed on my machine. https://github.com/fortra/impacket/issues/1562

**Comment by byt3bl33d3r** [comment]
@d0MeGaSt4 please just use Docker.  Kali is special.
