### ISSUE TITLE
No .csv output

### ISSUE THREAD

**Issue by i2507** [byt3bl33d3r/ItWasAllADream#4]
Hi, thanks for this tool.
However when I run ` docker run -it itwasalladream -u <my_account> -p <my_pwd> -d <my_domain> 192.168.1.0/24 -v`, there is no .csv output file in `itwasalladream` directory.

**Comment by byt3bl33d3r** [comment]
Docker 101 my dude https://docs.docker.com/engine/reference/commandline/cp/
