### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Finntroll-ru** [byt3bl33d3r/ItWasAllADream#5]
Hi,
thanks for your tool, there is an issue:

[itwasalladream] DEBUG - Target is single hostname
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:xxx.xxx.xxx.xxx/24[\PIPE\spoolss]
[itwasalladream] DEBUG - Started thread poller
[itwasalladream] DEBUG - [Errno Connection error (xxx.xxx.xxx.xxx/24:445)] [Errno -2] Name or service not known
[itwasalladream] DEBUG - [Errno -2] Name or service not known
[itwasalladream] INFO - Unable to determine if xxx.xxx.xxx.xxx/24 is vulnerable over MS-PAR. Reason: [Errno -2] Name or service not known
[itwasalladream] INFO - Unable to determine if xxx.xxx.xxx.xxx/24 is vulnerable over MS-RPRN. Reason: [Errno Connection error (xxx.xxx.xxx.xxx/24:445)] [Errno -2] Name or service not known
[itwasalladream] INFO - Scan complete, generating report. Please wait...
[itwasalladream] INFO - report_2021_07_07_095349.csv generated successfully

What can I do wrong?
Username, password and domain name are correct.
xxx.xxx.xxx.xxx - my local ip. With remote LAN IP is same result.
I tryed to use it to Windows 7, 8.1 and 10.

**Comment by byt3bl33d3r** [comment]
This was fixed. Thanks.
