### ISSUE TITLE
Feature request: accept multiple IP addresses (not just netblocks)

### ISSUE THREAD

**Issue by ripline** [byt3bl33d3r/ItWasAllADream#6]
Hi,

It would be super-helpful if IWAAD would accept multiple individual IP addresses, as well as netblocks, either on the command line or from a file.  This would be most beneficial on larger networks with sparse systems that are capable of being vulnerable.  I already have data on which systems are open on port 445 (masscan is more efficient at finding these), leaving IWAAD free to do the clever stuff.

Just a suggestion, if possible ?  

Thanks!

**Comment by byt3bl33d3r** [comment]
It already accepts multiple IP addresses from a newline-delimited file or CSV. I can add support for netblocks from a file later today.

**Comment by ripline** [comment]
Thanks!

**Comment by seajaysec** [comment]
@byt3bl33d3r it seems inconsistent at parsing target lists from newline-delimited files and CSV's. receiving this output on a large list (over 500 hosts) but it runs fine on a list of a few dozen.

```
[itwasalladream] INFO - Unable to determine if temp.txt is vulnerable over MS-RPRN. Reason: [Errno Connection error (tws.txt:445)] [Errno -2] Name or service not known
[itwasalladream] INFO - Unable to determine if temp.txt is vulnerable over MS-PAR. Reason: [Errno -2] Name or service not known
[itwasalladream] INFO - Scan complete, generating report. Please wait...
```

**Comment by byt3bl33d3r** [comment]
@seajaysec you 100% sure the path you're giving to the file valid ? This works perfectly for me. Can you paste the path you're giving it here? Thanks

**Comment by seajaysec** [comment]
@byt3bl33d3r The file with the targets is in the ItWasAllADream directory and gives that same output when called like `docker run -it itwasalladream -u USERNAME -d DOMAIN targets.txt` and `docker run -it itwasalladream -u USERNAME -d DOMAIN ./targets.txt`. I tried creating the target txt in vscode and vim, and leaving a trailing newline, but it produces the same output. Same when changing it to CSV and adding the default header to the top of the file.

**Comment by Verrideo** [comment]
I am having the same problem although can't get it to work with any .txt or .csv files at all. I just receive the message @seajaysec gets whereby it looks like the script is trying to use the filename as an IP instead of ingesting it's contents.

**Comment by Verrideo** [comment]
debug log also shows that is has identified the target as a single hostname

**Comment by byt3bl33d3r** [comment]
Ill take a look at this in a bit.

**Comment by byt3bl33d3r** [comment]
```
λ → itwasalladream -v -u gesu -p Passw0rd! -d PORCODIO test.txt 
[itwasalladream] DEBUG - Target is newline-delimited file
itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:192.168.1.1[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:192.168.1.2[\PIPE\spoolss]
```

```
 λ → itwasalladream -v -u gesu -p Passw0rd! -d PORCODIO /home/byt3bl33d3r/Devel/ItsJustADream/test.txt
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:192.168.1.1[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:192.168.1.2[\PIPE\spoolss]
```

Works for me both with a txt and csv file....

@seajaysec // @Verrideo you're using docker, have you passed the target file through to the container? you can't just point to the file on your local system as your running the tool from inside the docker container. you need to do a `-v ` argument when running the tool. `docker run -v path/to/file/on/local/system.txt:/path/inside/container.txt -it itwasalladream -u USERNAME -d DOMAIN /path/inside/container.txt`

**Comment by byt3bl33d3r** [comment]
@ripline you can now put hostnames, individual IPs and netblox in a txt/csv file:

```
λ → cat test.txt 
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: test.txt
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ wat.diocane.corp
   2   │ 192.168.1.1
   3   │ 10.0.0.1/24
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
λ → itwasalladream -v -u gesu -p Passw0rd! -d PORCODIO test.txt
[itwasalladream] DEBUG - Target is newline-delimited file
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:wat.diocane.corp[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:192.168.1.1[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.0[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.1[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.2[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.3[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.4[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.5[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.6[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.7[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.8[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.9[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.10[\PIPE\spoolss]
[itwasalladream.rprn_vector] DEBUG - Connecting to ncacn_np:10.0.0.11[\PIPE\spoolss]
...
```

**Comment by byt3bl33d3r** [comment]
Closing since the latest commit addresses the original issue. Please open a new one if my comment above about docker doesn't resolve the other issue.

**Comment by seajaysec** [comment]
Oh yeah, it was the issue with not passing the list to docker properly. That's solved it. Thank you!!
