### ISSUE TITLE
How to get the csv ?

### ISSUE THREAD

**Issue by jebailie** [byt3bl33d3r/ItWasAllADream#7]
It seems to be working... but how do I get the csv ?

`[itwasalladream] INFO - report_2021_07_07_213107.csv generated successfully`

The file _presumably_ is on the docker, which is not running and won't answer to anything but the args required.

**Comment by pageinsec** [comment]
Byt3bl33d3r's response in closed issue: https://docs.docker.com/engine/reference/commandline/cp/

Pull out of the image using the cp option.

**Comment by byt3bl33d3r** [comment]
Again this Docker 101 stuff... I don't think it's expected that I give a docker tutorial in the README. 

Take a look at the `docker cp`command, docker volumes and/or bind mounts.

**Comment by hSinding** [comment]
@jebailie  There are probably better ways of doing it, but you can do it like this.
docker ps -a (This will give you a list of containers, take the "name")
and do a docker cp NAME:CSVNAME PATHONTHESERVERAREON

so it could look like this: 
docker cp quizzical_busy:report_2021_07_08_094504.csv .

@byt3bl33d3r Thank you for your work!

**Comment by jebailie** [comment]
@hSinding Thanks! Success! ... (Sometimes it's the simplest things that are the hardest...)
